/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as TerugInDeTijdRouteImport } from './routes/terug-in-de-tijd'
import { Route as MeevarenOostzeeRouteImport } from './routes/meevaren-oostzee'
import { Route as LogboekRouteImport } from './routes/logboek'
import { Route as BoekJouwAvontuurRouteImport } from './routes/boek-jouw-avontuur'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogboekSlugRouteImport } from './routes/logboek_.$slug'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const TerugInDeTijdRoute = TerugInDeTijdRouteImport.update({
  id: '/terug-in-de-tijd',
  path: '/terug-in-de-tijd',
  getParentRoute: () => rootRouteImport,
} as any)
const MeevarenOostzeeRoute = MeevarenOostzeeRouteImport.update({
  id: '/meevaren-oostzee',
  path: '/meevaren-oostzee',
  getParentRoute: () => rootRouteImport,
} as any)
const LogboekRoute = LogboekRouteImport.update({
  id: '/logboek',
  path: '/logboek',
  getParentRoute: () => rootRouteImport,
} as any)
const BoekJouwAvontuurRoute = BoekJouwAvontuurRouteImport.update({
  id: '/boek-jouw-avontuur',
  path: '/boek-jouw-avontuur',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogboekSlugRoute = LogboekSlugRouteImport.update({
  id: '/logboek_/$slug',
  path: '/logboek/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boek-jouw-avontuur': typeof BoekJouwAvontuurRoute
  '/logboek': typeof LogboekRoute
  '/meevaren-oostzee': typeof MeevarenOostzeeRoute
  '/terug-in-de-tijd': typeof TerugInDeTijdRoute
  '/tracker': typeof TrackerRoute
  '/logboek/$slug': typeof LogboekSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boek-jouw-avontuur': typeof BoekJouwAvontuurRoute
  '/logboek': typeof LogboekRoute
  '/meevaren-oostzee': typeof MeevarenOostzeeRoute
  '/terug-in-de-tijd': typeof TerugInDeTijdRoute
  '/tracker': typeof TrackerRoute
  '/logboek/$slug': typeof LogboekSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boek-jouw-avontuur': typeof BoekJouwAvontuurRoute
  '/logboek': typeof LogboekRoute
  '/meevaren-oostzee': typeof MeevarenOostzeeRoute
  '/terug-in-de-tijd': typeof TerugInDeTijdRoute
  '/tracker': typeof TrackerRoute
  '/logboek_/$slug': typeof LogboekSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boek-jouw-avontuur'
    | '/logboek'
    | '/meevaren-oostzee'
    | '/terug-in-de-tijd'
    | '/tracker'
    | '/logboek/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boek-jouw-avontuur'
    | '/logboek'
    | '/meevaren-oostzee'
    | '/terug-in-de-tijd'
    | '/tracker'
    | '/logboek/$slug'
  id:
    | '__root__'
    | '/'
    | '/boek-jouw-avontuur'
    | '/logboek'
    | '/meevaren-oostzee'
    | '/terug-in-de-tijd'
    | '/tracker'
    | '/logboek_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoekJouwAvontuurRoute: typeof BoekJouwAvontuurRoute
  LogboekRoute: typeof LogboekRoute
  MeevarenOostzeeRoute: typeof MeevarenOostzeeRoute
  TerugInDeTijdRoute: typeof TerugInDeTijdRoute
  TrackerRoute: typeof TrackerRoute
  LogboekSlugRoute: typeof LogboekSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terug-in-de-tijd': {
      id: '/terug-in-de-tijd'
      path: '/terug-in-de-tijd'
      fullPath: '/terug-in-de-tijd'
      preLoaderRoute: typeof TerugInDeTijdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meevaren-oostzee': {
      id: '/meevaren-oostzee'
      path: '/meevaren-oostzee'
      fullPath: '/meevaren-oostzee'
      preLoaderRoute: typeof MeevarenOostzeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logboek': {
      id: '/logboek'
      path: '/logboek'
      fullPath: '/logboek'
      preLoaderRoute: typeof LogboekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boek-jouw-avontuur': {
      id: '/boek-jouw-avontuur'
      path: '/boek-jouw-avontuur'
      fullPath: '/boek-jouw-avontuur'
      preLoaderRoute: typeof BoekJouwAvontuurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logboek_/$slug': {
      id: '/logboek_/$slug'
      path: '/logboek/$slug'
      fullPath: '/logboek/$slug'
      preLoaderRoute: typeof LogboekSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoekJouwAvontuurRoute: BoekJouwAvontuurRoute,
  LogboekRoute: LogboekRoute,
  MeevarenOostzeeRoute: MeevarenOostzeeRoute,
  TerugInDeTijdRoute: TerugInDeTijdRoute,
  TrackerRoute: TrackerRoute,
  LogboekSlugRoute: LogboekSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
